name: Robert Pooley
# avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
bio: 1337 H4x0r
# company: Company # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: Austin, TX # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params:
  layout: compact
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  email: robpol86@gmail.com
  github: Robpol86/robpol86.com
  twitter: Robpol86
  rss: ""  # Remove RSS
