baseURL: http://localhost:1313/
title: Robpol86.com
theme: github.com/razonyang/hugo-theme-bootstrap
copyright: 'Copyright © {year} Robpol86'
defaultContentLanguage: en
paginate: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
disqusShortname: rob86wiki

blackfriday:  # TODO check out other types: https://gohugo.io/getting-started/configuration-markup/
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

permalinks:
  news: /news/:year/:month/:title/
  blog: /blog/:year/:month/:title/

# module:
  # proxy: https://goproxy.cn
