version: 2

jobs:
    build:
        machine: true
        working_directory: ~/project

        steps:
            - checkout

            - run:
                name: Install Dependencies
                command: |
                    curl -fsSL https://download.docker.com/linux/ubuntu/gpg |sudo apt-key add -
                    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
                    sudo add-apt-repository -y ppa:jonathonf/python-3.6
                    sudo apt-get update
                    sudo apt-get install -y docker-ce python3.6
                    curl https://bootstrap.pypa.io/get-pip.py |sudo python3.6
                    sudo pip3.6 install tox

            - run:
                name: Build Docker Image
                command : |
                    pushd $(mktemp -d) && mkdir -p htdocs/sub htdocs/branch
                    cp ~/project/tests/Dockerfile .
                    cp ~/project/docs/.htaccess htdocs/
                    echo "Hello World" > htdocs/index.html
                    echo "Hello Sub" > htdocs/sub/sub.html
                    echo "This is the 404 page." > htdocs/404.html
                    echo "Hello ImageCFG" > htdocs/imagecfg.html
                    echo "Hello ImageCFG2" > htdocs/branch/imagecfg.html
                    echo "Hello Lapdock" > htdocs/lapdock.html
                    echo "Hello Berto89" > htdocs/berto89.iso
                    docker build -t httpd_alpine .

            - run:
                name: Lint and Test
                command: tox

            - deploy:
                name: Upload Docs
                command: |
                    git config --global user.email "builds@circleci.com"
                    git config --global user.name "CircleCI"
                    git remote add nfsn "robpol86_robpol86@ssh.phx.nearlyfreespeech.net:/home/private/repo"
                    tox -e docsV
