[build]
publish = "public"

[build.environment]
NODE_VERSION = "17.6.0"
HUGO_VERSION = "0.97.3"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.17.7"

[context.production]
command = "npm install && hugo --minify"

[context.production.environment]
HUGO_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/:lang/*"
  to = "/:lang/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
