{
 "title": "TNAS",
 "description": "https://robpol86.com/posts/2025/2025-07-23-truenas-scale-telegraf.html",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "BUCKET", "query": "${VAR_BUCKET}" },
   { "name": "NAS_HOST", "query": "${VAR_NAS_HOST}" },
   {
    "name": "dsBuckets",
    "query": "${BUCKET}=now:-1d|\n${BUCKET}_1m=-1d:-7d|\n${BUCKET}_5m=-7d:-30d|\n${BUCKET}_10m=-30d:inf"
   },
   {
    "name": "dsPost",
    "query": {
     "query": "// BSD 2-Clause License\n// Copyright (c) 2025, Robpol86\n// All rights reserved.\n// Redistribution and use in source and binary forms, with or without\n// modification, are permitted provided that the following conditions are met:\n// 1. Redistributions of source code must retain the above copyright notice, this\n//    list of conditions and the following disclaimer.\n// 2. Redistributions in binary form must reproduce the above copyright notice,\n//    this list of conditions and the following disclaimer in the documentation\n//    and/or other materials provided with the distribution.\n// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"\n// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\n// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE\n// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR\n// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\n// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nimport \"array\"\nimport \"date\"\nimport \"strings\"\n\n// Take in any string array and outputs it as a stream so Grafana can ingest it as a single or multi-value variable.\nexportAsStream = (arr) =>\n    array.from(rows: array.map(arr: arr, fn: (x) => ({ _value: x })))\n\n// Convert time strings (e.g. \"now\" or \"-3d\") into time objects.\nstringToTime = (s) =>\n    if s == \"now\" then now()\n    else if s == \"inf\" or s == \"-inf\" then date.time(t: inf)\n    else date.time(t: duration(v: s))\n\n// Parse dsBuckets string into array of strings and stop/stop time objects bound within the range of trStart/trStop.\nparseBucketsString = (buckets, trStop, trStart) =>\n    // Split dsBuckets string with pipe delimiter. Valid string example: telegraf=now:-5m|telegraf_1m=-5m:-inf\n    strings.split(v: buckets, t: \"|\")\n        |> array.map(fn: (x) => strings.trimSpace(v: x))\n        // Filter out invalid substrings.\n        |> array.filter(fn: (x) => x =~ /^[a-zA-Z0-9_-]+=[a-z0-9-]+:[a-z0-9-]+$/)\n        // Get bucket names and convert start/stop to time objects.\n        |> array.map(fn: (x) => {\n            // Split and get the bucket name.\n            splitEquals = strings.splitN(v: x, t: \"=\", i: 2)\n            name = splitEquals[0]\n            // Split and get the bucket time range.\n            splitColon = strings.splitN(v: splitEquals[1], t: \":\", i: 2)\n            bStop = stringToTime(s: splitColon[0])\n            bStart = stringToTime(s: splitColon[1])\n            return {name, bStop, bStart}\n            })\n        // Filter out buckets outside of selected time range.\n        |> array.filter(fn: (x) => x.bStart < trStop and x.bStop > trStart)\n        // Adjust start/stop time boundaries for outer buckets.\n        |> array.map(fn: (x) => {\n            name = x.name\n            stop = if trStop < x.bStop then trStop else x.bStop\n            start = if trStart > x.bStart then trStart else x.bStart\n            return {name, stop, start}\n            })\n\n// Return the dsQuery() Flux function call that Grafana will execute for one bucket.\ndsPostSingle = (bucket) =>\n    \"dsQuery(bucket: \\\"${bucket.name}\\\", start: ${bucket.start}, stop: ${bucket.stop})\"\n\n// Return one dsQuery() call per bucket and route the outputs into union() to merge them into one metric.\n// Normalize start/stop boundary times so Grafana displays them as one line.\ndsPostMulti = (parsedBuckets, trStop, trStart) => {\n    dsQueryCalls = array.map(arr: parsedBuckets, fn: (x) => dsPostSingle(bucket: x))\n    dsQueryArr = \"[\" + strings.joinStr(arr: dsQueryCalls, v: \", \") + \"]\"\n    dsQueryUnion = \"union(tables: ${dsQueryArr})\"\n    return \"map(tables: ${dsQueryUnion}, fn: (r) => ({ r with _start: ${trStart}, _stop: ${trStop} }))\"\n}\n\n// Main.\nbuckets = ${dsBuckets:doublequote}\ndsPost =\n    if buckets !~ /\\b(now)\\b/\n    then \"error: 'now' is missing\"\n    else if buckets !~ /\\b(inf)\\b/\n    then \"error: 'inf' is missing\"\n    else () => {\n        trStop = v.timeRangeStop\n        trStart = v.timeRangeStart\n        parsedBuckets = parseBucketsString(buckets, trStop, trStart)\n        return\n            if length(arr: parsedBuckets) < 1\n            then \"error: no valid buckets\"\n            else if length(arr: parsedBuckets) == 1\n            then dsPostSingle(bucket: parsedBuckets[0])\n            else dsPostMulti(parsedBuckets, trStop, trStart)\n    }()\nexportAsStream(arr: [dsPost])"
    }
   }
  ]
 },
 "panels": [
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The host's most recently reported uptime in human readable format",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${BUCKET}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"uptime\")\n  |> drop(columns: [\"host\"])\n  |> last()\n  |> map(fn: (r) => {\n      // uptime_format is deprecated: https://github.com/influxdata/telegraf/blob/59234e6/plugins/inputs/system/README.md?plain=1#L46\n      // https://github.com/influxdata/telegraf/blob/59234e6/plugins/inputs/system/system.go#L89\n      uptime = r._value\n      days = int(v: uptime / (60 * 60 * 24))\n      uptimeFormatDays =\n        if days > 1 then \"${days} days, \"\n        else if days == 1 then \"${days} day, \"\n        else \"\"\n      seconds = int(v: uptime % 60)\n      uptimeFormatSeconds = if seconds < 10 then \"0${seconds}\" else \"${seconds}\"\n      minutes_ = uptime / 60\n      hours = int(v: (minutes_ / 60) % 24)\n      minutes = int(v: minutes_ % 60)\n      uptimeFormatMinutes = if minutes < 10 then \"0${minutes}\" else \"${minutes}\"\n      uptimeFormat = \"${hours}:${uptimeFormatMinutes}:${uptimeFormatSeconds}\"\n      return { r with _value: \"${uptimeFormatDays}${uptimeFormat}\" }\n  })"
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "SSD/HDD Temperature",
   "type": "timeseries",
   "description": "The internal temperature of each drive",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"smart_attribute\")\n  |> filter(fn: (r) => r._field == \"raw_value\")\n  |> filter(fn: (r) => r.name == \"Temperature_Celsius\")\n  |> drop(columns: [\"device\"])\n  |> toFloat()\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  {
   "title": "SSD/HDD Additional Temperature",
   "type": "timeseries",
   "description": "Additional temperature sensors for each drive",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"smart_attribute\")\n  |> filter(fn: (r) => r._field == \"raw_value\")\n  |> filter(fn: (r) => r.name =~ /(Temperature_Sensor_|Airflow_Temperature)/)\n  |> drop(columns: [\"device\"])\n  |> toFloat()\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "description": "CPU temperatures per core",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"sensors\")\n  |> filter(fn: (r) => r._field == \"temp_input\")\n  |> filter(fn: (r) => r.feature =~ /core_/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  {
   "title": "System Temperature",
   "type": "timeseries",
   "description": "System temperatures",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"sensors\")\n  |> filter(fn: (r) => r._field == \"temp_input\")\n  |> filter(fn: (r) => r.feature =~ /package|temp/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "description": "CPU fan speed",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"sensors\")\n  |> filter(fn: (r) => r._field == \"fan_input\")\n  |> filter(fn: (r) => r.feature == \"fan2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  { "title": "Space Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Datasets Used Space",
   "type": "timeseries",
   "description": "Space used by each ZFS dataset (does not include child datasets)",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"exec_zfs_list\")\n  |> filter(fn: (r) => r._field == \"referenced\")\n  |> filter(fn: (r) => r._value > 1024 * 1024 * 100)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  {
   "title": "Pools Free Space",
   "type": "timeseries",
   "description": "Free space for each ZFS pool",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"exec_zfs_list\")\n  |> filter(fn: (r) => r._field == \"available\")\n  |> filter(fn: (r) => r.name =~ /^[^\\/]+$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  { "title": "SSD Faults", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Unsafe Shutdowns",
   "type": "timeseries",
   "description": "Number of unsafe shutdowns. This count is incremented when a\nshutdown notification (CC.SHN) is not received prior to loss of power.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"smart_attribute\")\n  |> filter(fn: (r) => r._field == \"raw_value\")\n  |> filter(fn: (r) => r.name == \"Unsafe_Shutdowns\")\n  |> drop(columns: [\"device\"])\n  |> toFloat()\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  {
   "title": "Available Spare",
   "type": "timeseries",
   "description": "Percentage of available spare space (spare space for bad block mapping)",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"smart_attribute\")\n  |> filter(fn: (r) => r._field == \"raw_value\")\n  |> filter(fn: (r) => r.name == \"Available_Spare\")\n  |> drop(columns: [\"device\"])\n  |> toFloat()\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  {
   "title": "Percentage Used",
   "type": "timeseries",
   "description": "A vendor specific estimate of the percentage of NVM subsystem life used\nbased on the actual usage and the manufacturer’s prediction of NVM life. A value of 100 indicates that\nthe estimated endurance of the NVM in the NVM subsystem has been consumed, but may not indicate\nan NVM subsystem failure. The value is allowed to exceed 100. Percentages greater than 254 shall be\nrepresented as 255.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"smart_attribute\")\n  |> filter(fn: (r) => r._field == \"raw_value\")\n  |> filter(fn: (r) => r.name == \"Percentage_Used\")\n  |> drop(columns: [\"device\"])\n  |> toFloat()\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  {
   "title": "Temperature Times",
   "type": "timeseries",
   "description": "Contains the amount of time in minutes that the controller\nis operational and the temperature is greater than or equal to the Warning or Critical Composite\nTemperature Threshold.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"smart_attribute\")\n  |> filter(fn: (r) => r._field == \"raw_value\")\n  |> filter(fn: (r) => r.name =~ /Temperature_Time/)\n  |> drop(columns: [\"device\"])\n  |> toFloat()\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  { "title": "CPU, Memory, and IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Load Averages",
   "type": "timeseries",
   "description": "A metric that shows the number of tasks currently executed by the CPU and tasks waiting in the queue (ideally it's lower than the number of CPUs on the system, e.g. <4 for a 4-core CPU)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field =~ /^load\\d/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: \n      if r._field == \"load1\" then \"load  1\"\n      else if r._field == \"load5\" then \"load  5\" \n      else if r._field == \"load15\" then \"load 15\"\n      else r._field\n  }))\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU usage based on types of tasks (as reported by `top`)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"cpu\")\n  |> filter(fn: (r) => r.cpu == \"cpu-total\")\n  |> filter(fn: (r) => r._field =~ /usage_(user|system|nice|iowait|irq|softirq)/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory and swap usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"mem\" or r._measurement == \"swap\")\n  |> filter(fn: (r) => r._field == \"used\" or r._field == \"active\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "description": "Read and write operations involving a physical drive measured in bytes per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"diskio\")\n  |> filter(fn: (r) => r.DEVTYPE == \"disk\")\n  |> filter(fn: (r) => r._field == \"read_bytes\" or r._field == \"write_bytes\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> drop(columns: [\"name\", \"DEVLINKS\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Network traffic per interface measured in bits per second",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"net\")\n  |> filter(fn: (r) => r.interface =~ /enp.s0/)\n  |> filter(fn: (r) => r._field == \"bytes_recv\" or r._field == \"bytes_sent\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> map(fn: (r) => ({ r with _value: r._value * 8.0 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> rename(columns: {\"bytes_recv\": \"recv\", \"bytes_sent\": \"sent\"})\n${dsPost}"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "timeseries",
   "description": "Unit counts for TCP/UDP connection states from the `netstat` command",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "query": "dsQuery = (bucket, start, stop) =>\nfrom(bucket)\n  |> range(start, stop)\n  |> filter(fn: (r) => r.host == \"${NAS_HOST}\")\n  |> filter(fn: (r) => r._measurement == \"netstat\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n${dsPost}"
    }
   ]
  }
 ]
}