# https://github.com/microsoft/vscode-dev-containers/tree/v0.233.0/containers/python-3/.devcontainer/base.Dockerfile

ARG VARIANT="3.10-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}

# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends curl git i2c-tools jq lsof moreutils nmap pv telnet vim zsh socat unzip make python3-venv xsel psmisc

# RUN curl -sSL https://install.python-poetry.org |python3 -
