name: Setup Dependencies
description: Setup project dependencies.


runs:
  using: composite
  steps:

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: "20.6.1"

    - name: Install Dependencies
      shell: bash
      run: npm i


outputs:
  cache-hit:
    description: Poetry cache hit boolean
    value: ${{ steps.python.outputs.cache-hit }}
