name: Setup Dependencies
description: Setup project dependencies.


runs:
  using: composite
  steps:

    - name: Install Poetry
      shell: bash
      run: pipx install poetry

    - name: Configure Poetry
      shell: bash
      run: poetry config virtualenvs.in-project true

    - name: Install Python
      id: python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: poetry

    - name: Install dependencies
      shell: bash
      if: steps.python.outputs.cache-hit != 'true'
      run: poetry install


outputs:
  cache-hit:
    description: Poetry cache hit boolean
    value: ${{ steps.python.outputs.cache-hit }}
