name: Setup Dependencies
description: Setup project dependencies.


runs:
  using: composite
  steps:

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: Install Dependencies
      shell: bash
      run: make deps


outputs:
  cache-hit:
    description: Poetry cache hit boolean
    value: ${{ steps.python.outputs.cache-hit }}
