name: Setup Dependencies
description: Setup project dependencies.


runs:
  using: composite
  steps:

    - name: Install Poetry
      uses: abatilo/actions-poetry@v3

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: poetry

    - name: Install Dependencies
      shell: bash
      run: make deps


outputs:
  cache-hit:
    description: Poetry cache hit boolean
    value: ${{ steps.python.outputs.cache-hit }}
