name: Setup Dependencies
description: Setup project dependencies.


runs:
  using: composite
  steps:

    - name: TODO
      shell: bash
      run: echo TODO


outputs:
  cache-hit:
    description: Poetry cache hit boolean
    value: ${{ steps.python.outputs.cache-hit }}
