name: Update Version File
description: Update the version file.


inputs:
  new_version:
    description: New version string to apply
    required: false


runs:
  using: composite
  steps:

    - name: Update
      shell: bash
      env:
        NEW_VERSION: "${{ inputs.new_version }}"
        VERSION_FILE: pyproject.toml
      run: sed -i "0,/^version = /s/\"[^\"]\+\"/\"$NEW_VERSION\"/" "$VERSION_FILE"
