name: Update Version File
description: Update the version file.


inputs:
  new_version:
    description: New version string to apply
    required: false


runs:
  using: composite
  steps:

    - name: Update
      shell: bash
      env:
        AWK_PROGRAM: |
          /^version = / {
            if (!once) {
              once=1
              sub(/"[^"]+"/, "\""NEW_VERSION"\"")
            }
          }
          {
            print
          }
        NEW_VERSION: "${{ inputs.new_version }}"
        VERSION_FILE: pyproject.toml
      run: awk -i inplace -v NEW_VERSION="$NEW_VERSION" "$AWK_PROGRAM" "$VERSION_FILE"
