name: Prettify
description: De-minimize HTML, CSS, and other files for easier diffs

inputs:
  path:
    description: Directory path containing files to prettify
    required: true

runs:
  using: composite
  steps:
    - run: mv -v --no-clobber .git .git-backup || true
      shell: bash
    - uses: creyD/prettier_action@v3.3
      with:
        prettier_options: "--write ${{ inputs.path }}/**/*.{js,css,html,xml}"
        prettier_plugins: "@prettier/plugin-xml"
    - run: mv -v --no-clobber .git-backup .git || true
      shell: bash
      if: always()
