name: Continuous Integration

on:
  pull_request:
  push:

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2, with: {fetch-depth: 0}}
      - {name: Install Python, uses: actions/setup-python@v2, with: {python-version: "3.10"}}
      - {name: Install Poetry, uses: abatilo/actions-poetry@v2.1.4}
      - {name: Install dependencies, run: make deps}
      - {name: Run lints, run: make lint}
      - {name: Run tests, run: make test}
      - {name: Build docs, run: make docs}
