name: CI

on:
  pull_request:
  push: {branches-ignore: ["**_pr"]}

jobs:

  test:
    name: Test
    strategy:
      matrix:
        python: ["3.10"]  # TODO , "3.11"
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"
          cache: poetry

      # - name: Configure Poetry
      #   shell: bash
      #   run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        # if: "steps.validate.outputs.is-valid != 'true'"
        run: poetry install

      - name: Run tests
        env:
          PY_COLORS: 1
        run: make test

      - name: Run lints
        run: make lint

      - name: Run integration tests
        run: make it

      - name: Build docs
        run: make docs
