name: CI

on:
  pull_request:
  push: {branches-ignore: ["**_pr"]}

jobs:

  test:
    name: Test
    strategy:
      matrix:
        python: ["3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/init
        with:
          python-version: "${{ matrix.python }}"

      - name: Run tests
        env:
          PY_COLORS: 1
        run: make test

      - name: Run lints
        run: make lint

      - name: Run integration tests
        run: make it

      - name: Build docs
        run: make docs
