name: CI

on:
  pull_request:
  push:

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2, with: {fetch-depth: 0}}
      - {name: Install Python, uses: actions/setup-python@v2, with: {python-version: "3.10"}}
      - {name: Install Poetry, uses: abatilo/actions-poetry@v2.1.4}
      - {name: Cache venv, uses: actions/cache@v2, with: {path: .venv, key: "${{ runner.os }}-venv-${{ hashFiles('poetry.lock') }}"}, id: cache}
      - {name: Install dependencies, run: make deps, if: "steps.cache.outputs.cache-hit != 'true'"}
      - {name: Run lints, run: make lint}
      - {name: Build docs, run: make docs}
