name: CI

on:
  pull_request:
  push: {branches-ignore: ["**_pr"]}

jobs:

  test:
    name: Test
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Initialize dependencies
        uses: Robpol86/actions-init-deps-py@v3
        with:
          cache-buster: "${{ join(matrix.*, '|') }}"
          poetry-version: "1.2.1"
          python-version: "${{ matrix.python }}"

      - name: Run tests
        env:
          PY_COLORS: 1
        run: make test

      - name: Run lints
        run: make lint

      - name: Run integration tests
        run: make it

      - name: Build docs
        run: make docs

  linkcheck:
    name: Linkcheck
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Initialize dependencies
        uses: Robpol86/actions-init-deps-py@v3
        with:
          poetry-version: "1.2.1"
          python-version: "3.10"

      - name: Run linkcheck
        env:
          RETRY: 3
          SLEEP_FOR: 10
        run: |
          set -ex
          until make linkcheck; do
            if (( i++ < RETRY )); then
              echo Retrying...
              sleep "$SLEEP_FOR"
            else
              exit 1
            fi
          done
