name: CI

on:
  pull_request:
  push: {branches-ignore: ["**_pr"]}

jobs:

  test:
    name: Test
    strategy:
      matrix:
        python: ["3.8", "3.10", "3.11"] 
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.in-project true

      - name: Install Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"
          cache: poetry

      - name: Install dependencies
        if: steps.python.outputs.cache-hit != 'true'
        run: poetry install

      - name: Run tests
        env:
          PY_COLORS: 1
        run: make test

      - name: Run lints
        run: make lint

      - name: Run integration tests
        run: make it

      - name: Build docs
        run: make docs
