name: Continuous Integration

on:
  pull_request:
  push:

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2, with: {fetch-depth: 0}}
      - {name: Install Python, uses: actions/setup-python@v2, with: {python-version: "3.10"}}
      - {name: Install Poetry, uses: abatilo/actions-poetry@v2.1.4}
      - {name: Install dependencies, run: make deps}
      - {name: Run lints, run: make lint}
      - {name: Run tests, run: make test}
      - {name: Build docs, run: make docs}
      - name: Store HTML files artifact
        uses: actions/upload-artifact@v2
        with: {name: html, path: build/html/, if-no-files-found: error}

  lighthouse:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - {name: Install Python, uses: actions/setup-python@v2, with: {python-version: "3.10"}}
      - {name: Install xmlstarlet, run: sudo apt-get update && sudo apt-get install -y xmlstarlet}
      - {name: Fetch HTML files, uses: actions/download-artifact@v2, with: {name: html, path: html}}
      - run: mkdir reports
      - name: Start HTTP server
        run: |
          python3 -m http.server -d html 8000 &
          curl --retry 10 --retry-connrefused --retry-max-time 60 http://localhost:8000/index.html
      - name: Convert sitemap.xml into csv
        id: sitemap
        run: |
          echo -n "::set-output name=urls::"
          xmlstarlet sel -t -v "//*[local-name()='loc']/text()" html/sitemap.xml |tr "\n" ","
          echo
      - name: Run Lighthouse
        id: lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: reports
          urls: ${{ steps.sitemap.outputs.urls }}
          verbose: true
      - name: Verify Lighthouse
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouse.outputs.lighthouseCheckResults }}
          minAccessibilityScore: 1  # TODO: 96
          minBestPracticesScore: 1  # TODO: 85
          minPerformanceScore: 1  # TODO: 95
          minProgressiveWebAppScore: 1  # TODO: 50
          minSeoScore: 1  # TODO: 80
      - name: Store Lighthouse HTML report artifact
        uses: actions/upload-artifact@v2
        with: {name: lighthouse, path: reports/, if-no-files-found: error}
        if: always()
