name: Deploy


concurrency:
  cancel-in-progress: true
  group: staging  # TODO stage/prod separate


on:
  push:


jobs:

  Build:
    uses: ./.github/workflows/build.yml
    with:
      environment: staging
