name: Deploy


on:
  pull_request:


jobs:

  Build:
    uses: ./.github/workflows/build.yml
    with:
      environment: staging  # TODO staging/production
      skip_lints_tests: true

  Deploy:
    runs-on: ubuntu-latest
    environment: staging  # TODO staging/production
    needs: Build
    concurrency:
      cancel-in-progress: true
      group: "deploy-staging"  # TODO staging/production
    steps:
      - name: Download HTML
        uses: actions/download-artifact@v3
        with:
          name: html
          path: html
      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          known_hosts: "${{ vars.SSH_KNOWN_HOSTS }}"
      - name: Rsync
        env:
          SSH_HOST: "${{ vars.SSH_HOST }}"
          SSH_USER: "${{ secrets.SSH_USER }}"
        run: rsync -rptcivh --delete-after --stats ./html/ "$SSH_USER@$SSH_HOST:/home/public"
      - name: Purge Cloudflare Cache
        env:
          CF_AUTH: "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}"
          CF_URL: "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache"
        run: curl -f "$CF_URL" -H "$CF_AUTH" --data '{"purge_everything":true}'
