name: Diff

on:
  pull_request:

jobs:

  build:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Initialize dependencies
        uses: Robpol86/actions-init-deps-py@v3
        with:
          no-dev: "true"
      - name: Build docs
        env:
          SPHINX_GITHUB_BRANCH: main
          SPHINX_HTML_BASEURL: "https://rob86stage.robpol86.com/"
        run: make docs
      - name: Prettify
        uses: ./.github/actions/prettify
        with:
          path: build/html
      - name: Store HTML
        uses: actions/upload-artifact@v2
        with:
          name: html_feature
          if-no-files-found: error
          path: build/html/

  fetch:
    name: Fetch Pre-Release HTML
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download pre-release asset
        env:
          URL: "https://github.com/${{ github.repository }}/releases/download/_pre-release/html.tar.gz"
        run: |
          mkdir build
          until wget "$URL" -O html.tar.gz; do sleep 5; done
          tar -C build -xzvf html.tar.gz
        timeout-minutes: 1
      - name: Prettify
        uses: ./.github/actions/prettify
        with:
          path: build/html
      - name: Store HTML
        uses: actions/upload-artifact@v2
        with:
          name: html_pre
          if-no-files-found: error
          path: build/html/

  diff:
    name: Diff
    runs-on: ubuntu-latest
    needs: [fetch, build]
    steps:
      - name: Fetch this feature build
        uses: actions/download-artifact@v2
        with:
          name: html_feature
          path: html_feature
      - name: Fetch latest pre-release
        uses: actions/download-artifact@v2
        with:
          name: html_pre
          path: html_pre
      - name: Clean
        run: "find . '(' -name __pycache__ -o -name .doctrees ')' -type d -exec rm -rv {} +"
      - name: Diff
        id: diff
        run: |
          diff --color=always --recursive html_pre/ html_feature/ || true
          diff --color=never --recursive html_pre/ html_feature/ > all.diff || true
          if [ -s all.diff ]; then
            echo "::set-output name=nonzero::true"
            cp all{,-orig}.diff
            head -c 261445 all-orig.diff > all.diff
            if ! cmp -s all{,-orig}.diff; then
              echo -e "\n\nTruncated" >> all.diff
            fi
          fi
      - name: Post diff to PR if any changes are detected
        uses: actions/github-script@v5
        env:
          DIFF_NONZERO: "${{ steps.diff.outputs.nonzero }}"
        with:
          script: |
            const heading = 'Diff Against [Pre-Release](https://github.com/Robpol86/robpol86.com/releases/tag/_pre-release)'
            var body

            if (!process.env.DIFF_NONZERO) {
              body = '*No HTML changes detected.*'
            } else {
              const {promises: fs} = require('fs')
              const diff = (await fs.readFile('all.diff', 'utf8')).trim()
              body = '```diff\n' + diff + '\n```\n'

              // If diff is large collapse it to reduce clutter in the PR.
              let numLines = diff.match(/^/mg).length
              if (numLines > 10) {
                body = '<details>\n<summary>Show ' + numLines + ' lines</summary>\n\n' + body + '\n</details>'
              }
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '### ' + heading + '\n\n' + body
            })
