name: Linkcheck

on:
  push:

jobs:

  linkcheck:
    name: Linkcheck
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: ./.github/actions/deps
