name: Linkcheck

on:
  pull_request:
  push: {branches-ignore: ["**_pr"]}

jobs:

  linkcheck:
    name: Linkcheck
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Initialize dependencies
        uses: Robpol86/actions-init-deps-py@v3
        with:
          poetry-version: "1.2.1"
          python-version: "3.10"

      - name: Run linkcheck
        env:
          RETRY: 3
          SLEEP_FOR: 10
        run: |
          set -ex
          until make linkcheck; do
            if (( i++ < RETRY )); then
              echo Retrying...
              sleep "$SLEEP_FOR"
            else
              exit 1
            fi
          done
