name: Linkcheck

on:
  pull_request:
  push: {branches-ignore: ["**_pr"]}

jobs:

  linkcheck:
    name: Linkcheck
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.in-project true

      - name: Install Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry

      - name: Install dependencies
        if: steps.python.outputs.cache-hit != 'true'
        run: poetry install

      - name: Run linkcheck
        env:
          RETRY: 3
          SLEEP_FOR: 10
        run: |
          set -ex
          until make linkcheck; do
            if (( i++ < RETRY )); then
              echo Retrying...
              sleep "$SLEEP_FOR"
            else
              exit 1
            fi
          done
