name: Linkcheck

on:
  push:

jobs:

  linkcheck:
    name: Linkcheck
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: ./.github/actions/deps

      - name: Run linkcheck
        run: |
          set -eux
          if ! make linkcheck; then
            while read -r url; do
              curl -sSfv --retry 3 --retry-max-time 45 --retry-all-errors -o /dev/null -w "%{http_code}" "$url" > docs/_build/html/status.txt
              grep '^200$' docs/_build/html/status.txt
            done < docs/_build/html/broken.txt
          fi
