name: Deploy to Production

on:
  release: {types: [published]}

jobs:

  build:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2, with: {fetch-depth: 0}}
      - {name: Initialize dependencies, uses: ./.github/actions/init-deps}
      - {name: Build docs, run: make docs, env: {SPHINX_HTML_BASEURL: "https://robpol86.com/"}}
      - {name: Store HTML, uses: actions/upload-artifact@v2, with: {name: html, path: build/html/, if-no-files-found: error}}

  publish:
    name: Publish to NFSN
    needs: build
    concurrency: "publish-${{ github.event_name }}"
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Fetch HTML files, uses: actions/download-artifact@v2, with: {name: html, path: build/html/}}
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          source: build/html/
          user: "${{ secrets.NFSN_SSH_USER_PROD }}"
          ssh-key: "${{ secrets.NFSN_SSH_KEY }}"
          cf-token: "${{ secrets.TOKEN_CF_PURGE_CACHE }}"

  archive:
    name: Archive Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - {name: Fetch HTML files, uses: actions/download-artifact@v2, with: {name: html, path: html}}
      - {name: Archive HTML files, run: tar -czvf html.tar.gz html/}
      - name: Upload HTML Archive to Release
        uses: svenstaro/upload-release-action@v2
        with: {file: html.tar.gz, repo_token: "${{ secrets.GITHUB_TOKEN }}", tag: "${{ github.ref }}"}
