name: rpooley


on:
  push:


jobs:

  Test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Version File
        uses: ./.github/actions/version_bump
        with:
          new_version: "1.2.3.4"

      - name: Diff
        run: git diff
