name: Deploy to Staging

on:
  push: {branches: ["**"]}

jobs:

  build:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2, with: {fetch-depth: 0}}
      - {name: Initialize dependencies, uses: Robpol86/actions-init-deps-py@v3, with: {no-dev: "true"}}
      - {name: Build docs, run: make docs, env: {SPHINX_HTML_BASEURL: "https://rob86stage.robpol86.com/"}}
      - {name: Store HTML, uses: actions/upload-artifact@v2, with: {name: html, path: build/html/, if-no-files-found: error}}

  publish:
    name: Publish to NFSN
    runs-on: ubuntu-latest
    needs: build
    concurrency: "${{ github.workflow }}-${{ github.job }}"
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Fetch HTML files, uses: actions/download-artifact@v2, with: {name: html, path: build/html/}}
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          source: build/html/
          user: "${{ secrets.NFSN_SSH_USER_STAGE }}"
          ssh-key: "${{ secrets.NFSN_SSH_KEY }}"
          cf-token: "${{ secrets.TOKEN_CF_PURGE_CACHE }}"

  pre-release:
    name: Create Pre-release
    runs-on: ubuntu-latest
    needs: publish
    if: "github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, ' (#')"
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Fetch HTML files, uses: actions/download-artifact@v2, with: {name: html, path: build/html/}}
      - {name: Archive HTML files, run: tar -C build -czvf html.tar.gz html/}
      - {name: Get body, id: cl, uses: ./.github/actions/read-changelog, with: {section: "[Unreleased]", has_title: "false"}}
      - name: Get title
        id: commit
        run: 'jq -r .head_commit.message < "$GITHUB_EVENT_PATH" |head -1 |xargs -0 printf "::set-output name=title::%s"'
      - name: Delete existing pre-release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with: {delete_release: true, tag_name: _pre-release}
        env: {GITHUB_TOKEN: "${{ github.token }}"}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ steps.commit.outputs.title }}"
          body: "${{ steps.cl.outputs.body }}"
          tag_name: _pre-release
          prerelease: true
          target_commitish: "${{ github.ref }}"
          files: html.tar.gz
